[package]
name = "f128"
version = "0.1.3"
authors = ["Joshua Karns <jkarns275@gmail.com>"]
build = "build.rs"
license = "MIT"
description = "Bindings to the gcc quadmath library"

[dependencies]
num-traits = "0.2.6"
libc = "0.2"

[build-dependencies]
cc = "1.0"
